# Common configuration.
AllCops:
  # Include common Ruby source files.

  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'backup/**/*'
    - 'bundler_stubs/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - '.bundle/**/*'
    - 'config/initializers/**'
    - 'config/environments/**'
    - 'config/application.rb'
    - 'app/helpers/devise_helper.rb'

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  RequireForNonPublicMethods: false
  Enabled: false
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true